#:schema node_modules/wrangler/config-schema.json
name = "event-broker"
main = "src/index.js"
compatibility_date = "2024-08-21"
compatibility_flags = [ "nodejs_compat" ]

# Note: you must configure a secret, SIGNING_SECRET, with the signing secret for your rules
[vars]
MAX_FAILURE_COUNT = "5"

[[durable_objects.bindings]]
name = "EVENT_SUBSCRIPTIONS"
class_name = "EventSubscriptions"

[[migrations]]
tag = "v1"
new_classes = ["EventSubscriptions"]
